### ISSUE TITLE
Bug in the "catch up" pull

### ISSUE THREAD

**Issue by markstro-usgs** [nhm-usgs/onhm-fetcher-parser#1]
I think there are some crazy big values in the ncf file that you gave me for the historical period "catch up" last week. To see it, dump the ncf file into text with the ncdump command. Once you have the acsii file, search down to where the "prcp" values start. If you look in the first record (for the first time step) and count in 26 (I think it's 26) values, you will see a super giant precip value. This would be the value computed for HRU 26 on the first timestep. Can you please check this for me?

**Comment by rmcd-mscb** [comment]
Thanks Steve, this has been resolved.  UofI thredds server had changed their netcdf file format.  New code has resolved these changes with new weights.csv file for mapping netcdf gridded values to hru values
